colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 10
  showMoreLink = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showSummary = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showWordCount = true
  showComments = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showCards = true
  groupByYear = false
  cardView = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
